parameters:
  smartesb.consumers.queue.class: Smartbox\Integration\FrameworkBundle\Components\Queues\QueueConsumer
  smartesb.consumers.csv.class: Smartbox\Integration\FrameworkBundle\Components\FileService\Csv\CsvConfigurableConsumer

services:
  smartesb.consumers.queue:
      class: %smartesb.consumers.queue.class%
      calls:
          - [ setId, ['smartesb.consumers.queue']]
          - [ setSmartesbHelper, [@smartesb.helper]]