queues.generic:
  pattern: "queue://{queue_driver}/{queue}"
  defaults:
    _protocol: @smartesb.protocols.queue
    prefix: "%kernel.environment%"
  requirements:
    queue: "[a-zA-Z0-9/]+"
    queue_driver: "[a-zA-Z0-9]+"

direct:
  pattern: "direct://{path}"
  defaults:
    _protocol: @smartesb.protocols.direct
  requirements:
    path: "[a-zA-Z0-9/_]+"

service:
  pattern: "service://{service}/{method}"
  defaults:
    _protocol: @smartesb.protocols.service
  requirements:
    service: "[a-zA-Z0-9/_.-]+"
    method: "[a-zA-Z0-9_]+"

csv.generic:
  pattern: "csv://generic/{default_path}"
  defaults:
    _protocol: "@smartesb.protocols.configurable.csv_file"
    _consumer: "@smartesb.consumers.generic_csv"
    root_path: "/"
    delimiter: ","
    enclosure: '"'
    escape_char: '\'
    method: read_lines
  requirements:
    default_path: "[a-zA-Z0-9/\\-._]+"
