addons:
  hosts:
    - rabbit.local
    - database.local

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.7.*

matrix:
  allow_failures:
    - php: 7.1

before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - bash travis/install-apcu-pecl.sh || true
  - phpenv config-add travis.php.ini
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - bin/phpunit --coverage-text --debug

notifications:
  email:
    recipients:
      - si-integration@smartandco.com
    on_success: change 
    on_failure: always

services:
  - rabbitmq
  - mongodb
